/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pracmysql;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import pracmysql.Conexion.Conexion;
import pracmysql.clases.Areas;

/**
 *
 * @author xboxj
 */
public class Area extends javax.swing.JFrame {

    /**
     * Creates new form Area
     */
    Conexion con = new Conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    int modif;

    public Area(int n) {
        modif = n;
        initComponents();
        setLocationRelativeTo(null);
        mostar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID ");

        jLabel2.setText("Nombre");

        jLabel3.setText("Ubicacion");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid)
                            .addComponent(txtNombre)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        ventanas();
        if(modif==0){
            Agregar();
        }else{
            modificar();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ventanas();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    void ventanas(){
        Principal abrir = new Principal();
        abrir.setVisible(true);
        this.setVisible(false);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
////    public static void main(String args[]) {
////        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(Area.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new Area().setVisible(true);
////            }
////        });
////    }
    
    
    //metodo para agregar una nueva area
    void Agregar() {
        Areas area = new Areas(Integer.parseInt(txtid.getText()), txtNombre.getText(), txtUbicacion.getText());
        if (txtNombre.getText().equals("") || txtUbicacion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Las Cajas estan vacias!!!");
          
        } else {
            try {
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(area.toString());
                JOptionPane.showMessageDialog(null, "Area agregada");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e ,"ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    
    //metodo para modificar una area ya existente
    void modificar() {
        
      
        String nom = txtNombre.getText() ;
        String ubi = txtUbicacion.getText() ;
        
        String sql = "update areas set Nombre='" + nom + "',Ubicacion='" + ubi + "' where Id=" + modif;

        try {
            if (nom != null || ubi != null) {
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Area Modificada");

            } else {
                JOptionPane.showMessageDialog(null, "Error...!!!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e,"ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
    }

    
    //metodo que dependera si nuestra variable modif 
    //si esa variable trae un numero diferente de 0 entonces significa que vamos a modificar
    // en el caso contrario significa que vamos a ingresar una nueva area
    void mostar() {

        if (modif == 0) {
        } else {
            consulta();
            
        }
    }
    
    //metodo que nos ayuda a mostar en nuestros cuadros de texto  
    //cuando vamos a modificar 
    
    void consulta(){
        
            String sql = "select * from areas where id ="+modif ;
            try {
                cn = con.getConnection();
                st = cn.createStatement();
                rs = st.executeQuery(sql);
                Object[] persona = new Object[3];
                while (rs.next()) {
                    persona[0] = rs.getInt("id");
                    persona[1] = rs.getString("Nombre");
                    persona[2] = rs.getString("Ubicacion");
                }
                txtid.setText(persona[0].toString());
                txtNombre.setText(persona[1].toString());
                txtUbicacion.setText(persona[2].toString());
                
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e ,"ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUbicacion;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
